### PR TITLE
1 line hegiht

### PR DESCRIPTION
**Pull request by jbarreau**
Hello, 
I modify your lib because when the textarea is empty, I can't set the height to 1 line with a css hack.

without_modif
with_modif

.

### CODE REVIEW

**Comment by jevin** [comment]
Hi @jbarreau,
The opinions are divided on this. In some cases, the extra <br /> works fine, and it some cases it breaks. The only way to accept this PR would be if the line break was made into an option.

**Comment by jbarreau** [comment]
I add an option as you said for this feature; I did some tests, but I don't see any bugs with this modification.

**Comment by jevin** [comment]
Oh thanks for that, I'll check it out and let you know in a few.

**Comment by jevin** [comment]
Hello @jbarreau,

I ended up pushing a commit myself. See https://github.com/jevin/Autogrow-Textarea/commit/e282fc98b5dc00bbe6521712c64a3d194ea3854b#diff-3b3d5af78cfcff3ff3e86c812eee6810

This is what I was after. Now it's easy to add more options. ;-)

**Pull request closed without merging**
